# must be unique in a given SonarQube instance
sonar.projectKey=CCA.InfoSec.c_aakinsan_cyph3r_AZK_ofNSVOys-KC5S8fh
sonar.python.version=3.10.12
sonar.tests=cyph3r/tests 
sonar.exclusions=cyph3r/tests/*,cyph3r/tests/*/*,cyph3r/tests/*/*/*
sonar.branch.name=dev

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
#sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8