# Generated by Django 5.1.1 on 2024-10-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyph3r", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keygeneration",
            name="is_split",
            field=models.BooleanField(default=False),
        ),
    ]
