# Generated by Django 5.1.1 on 2024-10-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyph3r", "0005_remove_fileencryption_encrypted_with_key_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileEncryption",
        ),
        migrations.RemoveField(
            model_name="keysplit",
            name="key",
        ),
        migrations.DeleteModel(
            name="KeyGeneration",
        ),
        migrations.DeleteModel(
            name="KeySplit",
        ),
    ]
