name: cyph3r-workflow-jobs
on:
  push:

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Tools
        run: | 
          python -m pip install --upgrade pip
          pip install ruff black bandit

      - name: Run Black (check formatting)
        run: black --check .
        continue-on-error: true

      - name: Run Ruff (linting)
        run: ruff check .
        continue-on-error: true
      
      - name: Run Gitleaks (secret scanning)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --exclude-path=tests/ --report-path=gitleaks-report.json

      - name: Run Bandit (security analysis)
        run: bandit -c bandit.yaml -r . -f json -o bandit-report.json
        
      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: | 
            bandit-report.json
            gitleaks-report.json